version: '3'

services:
  frontend:
    build:
      context: .
      args:
        GIT_COMMIT: ${GIT_COMMIT}
    image: registry.jz17demo.acntech.no:5000/jz17-frontend-app/${FORMATTED_BRANCH_NAME}:${BUILD_NUMBER}
